spring:
  application:
    name: tst-service
  config:
    import: "configserver:"
  cloud:
    config:
      uri: http://${CONFIG_SERVER}:8888
      username: configUser
      password: configPassword
