### 관리자 Login 요청
POST {{api-service}}/api/auth/adminLogin
Content-Type: application/json
Accept: application/json

{
  "adminId": "TEST001",
  "passwd": "test1234"
}

> {%
    client.global.set("accessToken", response.headers.valuesOf("Set-Cookie")
        .find(function(cookie) { return (cookie.split(";")[0].split("=")[0] === "accessToken"); } ).split(";")[0].split("=")[1]
    );
    client.global.set("refreshToken", response.headers.valuesOf("Set-Cookie")
        .find(cookie => cookie.split(";")[0].split("=")[0] === "refreshToken").split(";")[0].split("=")[1]
    );
    client.log("global 쿠키: accessToken="+client.global.get("accessToken") + "\n          refreshToken="+ client.global.get("refreshToken"));
%}

### 청구 리스트 조회 (이전청구)
GET {{api-service}}/api/sals/billing/demands?clcdYn=CLCD_Y&startDt=2024-12-01&endDt=2025-12-31&page=0&size=15
Content-Type: application/json
Cookie: accessToken={{accessToken}}; refreshToken={{refreshToken}}

### 청구 리스트 조회 (미청구)
GET {{api-service}}/api/sals/billing/demands?clcdYn=CLCD_N&startDt=2025-07-01&endDt=2025-12-31
Cookie: accessToken={{accessToken}}; refreshToken={{refreshToken}}

### 청구 리스트 조회 (미청구 -국내)
GET {{api-service}}/api/sals/billing/demands/domestic?clcdYn=CLCD_N&startDt=2025-07-01&endDt=2025-12-31
Cookie: accessToken={{accessToken}}; refreshToken={{refreshToken}}

### 청구 리스트 조회 (미청구 -해외)
GET {{api-service}}/api/sals/billing/demands/foreign?clcdYn=CLCD_N&startDt=2025-11-01&endDt=2025-11-30
Cookie: accessToken={{accessToken}}; refreshToken={{refreshToken}}

### 청구 리스트 조회 (거래처 필터링)
GET {{api-service}}/api/sals/billing/demands?clcdYn=CLCD_Y&startDt=2025-12-01&endDt=2025-12-31&custCd=CUST001&page=0&size=15
Cookie: accessToken={{accessToken}}; refreshToken={{refreshToken}}

### 청구서 생성 (마감)
POST {{api-service}}/api/sals/billing/demands
Content-Type: application/json
Cookie: accessToken={{accessToken}}; refreshToken={{refreshToken}}

{
  "custCd": "CUST001",
  "demandDt": "2025-12-31",
  "demandStartDt": "2025-12-01",
  "demandStndDt": "2025-12-31",
  "exrtId": null,
  "demandMemo": "12월 정산 테스트"
}

> {%
    client.global.set("demandId", response.body.demandId);
    client.log("Created demandId: " + client.global.get("demandId"));
%}

### 청구 상세 조회
GET {{api-service}}/api/sals/billing/demands/{{demandId}}
Cookie: accessToken={{accessToken}}; refreshToken={{refreshToken}}

### 매출전표 생성
POST {{api-service}}/api/sals/billing/demands/{{demandId}}/sales-statements
Content-Type: application/json
Cookie: accessToken={{accessToken}}; refreshToken={{refreshToken}}

> {%
    client.global.set("slstmtNo", response.body.slstmtNo);
    client.log("Created slstmtNo: " + client.global.get("slstmtNo"));
%}

### 청구서 취소 (매출전표 생성 전에만 가능)
DELETE {{api-service}}/api/sals/billing/demands/{{demandId}}
Cookie: accessToken={{accessToken}}; refreshToken={{refreshToken}}
