### 관리자 Login 요청
POST {{api-service}}/api/auth/adminLogin
Content-Type: application/json
Accept: application/json

{
  "adminId": "TEST003",
  "passwd": "test1234"
}

> {% 
    client.global.set("accessToken", response.headers.valuesOf("Set-Cookie")
        .find(function(cookie) { return (cookie.split(";")[0].split("=")[0] === "accessToken"); } ).split(";")[0].split("=")[1]
    );
    client.global.set("refreshToken", response.headers.valuesOf("Set-Cookie")
        .find(cookie => cookie.split(";")[0].split("=")[0] === "refreshToken").split(";")[0].split("=")[1]
    );
    client.log("global 쿠키: accessToken="+client.global.get("accessToken") + "\n          refreshToken="+ client.global.get("refreshToken"));
%}

### 고객 추가정보(첨부문서) 목록 조회
GET {{api-service}}/api/sals/custs/atch-file
Content-Type: application/json
Accept: application/json
Cookie: accessToken={{accessToken}}; refreshToken={{refreshToken}}

### 고객 추가정보(첨부문서) 등록
POST {{api-service}}/api/sals/custs/atch-file
Content-Type: application/json
Cookie: accessToken={{accessToken}}; refreshToken={{refreshToken}}

{
  "custAtchFileId" : "DDF7D716-E498-4EE6-8391-F03160FA4E03",
  "custMstId": "DDF7D716-E498-4EE6-8391-F03160FA4E03",
  "custCd": "TESTCUST001",
  "atchGrupId": "ATCH_GRP_001",
  "useYn": true
}

### 고객 추가정보(첨부문서) 삭제
DELETE {{api-service}}/api/sals/custs/atch-file/1
Content-Type: application/json
Cookie: accessToken={{accessToken}}; refreshToken={{refreshToken}}