### 관리자 Login 요청
POST {{api-service}}/api/auth/adminLogin
Content-Type: application/json
Accept: application/json

{
  "adminId": "TEST003",
  "passwd": "test1234"
}

> {% 
    client.global.set("accessToken", response.headers.valuesOf("Set-Cookie")
        .find(function(cookie) { return (cookie.split(";")[0].split("=")[0] === "accessToken"); } ).split(";")[0].split("=")[1]
    );
    client.global.set("refreshToken", response.headers.valuesOf("Set-Cookie")
        .find(cookie => cookie.split(";")[0].split("=")[0] === "refreshToken").split(";")[0].split("=")[1]
    );
    client.log("global 쿠키: accessToken="+client.global.get("accessToken") + "\n          refreshToken="+ client.global.get("refreshToken"));
%}

### 고객 추가정보(연동정보) 단건 조회
GET {{api-service}}/api/sals/custs/rst-if-method/METHOD_ID_PLACEHOLDER
Content-Type: application/json
Accept: application/json
Cookie: accessToken={{accessToken}}; refreshToken={{refreshToken}}

### 고객 추가정보(연동정보) 저장
POST {{api-service}}/api/sals/custs/rst-if-method
Content-Type: application/json
Cookie: accessToken={{accessToken}}; refreshToken={{refreshToken}}

{
  "reqRstIfMethodId": "DDF7D716-E498-4EE6-8391-F03160FA4E03",
  "custMstId": "DDF7D716-E498-4EE6-8391-F03160FA4E03",
  "applyStartDt": "2023-01-01",
  "custCd": "TESTCUST001",
  "applyEndDt": null,
  "reqMethodCd": "REQ_M_01",
  "reqIfTypeCd": "IF_T_01",
  "useYn": true
}
