### 관리자 Login 요청 (테스트용)
POST {{api-service}}/api/auth/adminLogin
Content-Type: application/json
Accept: application/json

{
  "adminId": "TEST003",
  "passwd": "test1234"
}

> {%
    client.global.set("accessToken", response.headers.valuesOf("Set-Cookie")
        .find(function(cookie) { return (cookie.split(";")[0].split("=")[0] === "accessToken"); } ).split(";")[0].split("=")[1]
    );
    client.global.set("refreshToken", response.headers.valuesOf("Set-Cookie")
        .find(cookie => cookie.split(";")[0].split("=")[0] === "refreshToken").split(";")[0].split("=")[1]
    );
    client.log("global 쿠키: accessToken="+client.global.get("accessToken") + "\n          refreshToken="+ client.global.get("refreshToken"));
%}

###########################
# 검체용기 (Specimen Container)
###########################

### 검체용기 목록 조회 (전체)
GET {{api-service}}/api/tst/bbs/spcm-cntn
Content-Type: application/json
Accept: application/json
Cookie: accessToken={{accessToken}}; refreshToken={{refreshToken}}

### 검체용기 목록 조회 (이름으로 검색)
GET {{api-service}}/api/tst/bbs/spcm-cntn?cntnNm=test
Content-Type: application/json
Accept: application/json
Cookie: accessToken={{accessToken}}; refreshToken={{refreshToken}}

### 검체용기 단건 조회
GET {{api-service}}/api/tst/bbs/spcm-cntn/CNTN001
Content-Type: application/json
Accept: application/json
Cookie: accessToken={{accessToken}}; refreshToken={{refreshToken}}

### 검체용기 등록
POST {{api-service}}/api/tst/bbs/spcm-cntn
Content-Type: application/json
Accept: application/json
Cookie: accessToken={{accessToken}}; refreshToken={{refreshToken}}

{
  "spcmCntnCd": "TEST_CNTN01",
  "cntnNm": "테스트 검체용기",
  "cntnEngNm": "Test Specimen Container",
  "sortOrder": 1
}

### 검체용기 수정
PUT {{api-service}}/api/tst/bbs/spcm-cntn/TEST_CNTN01
Content-Type: application/json
Accept: application/json
Cookie: accessToken={{accessToken}}; refreshToken={{refreshToken}}

{
  "cntnNm": "수정된 검체용기",
  "cntnEngNm": "Updated Container",
  "sortOrder": 2
}

### 검체용기 삭제
DELETE {{api-service}}/api/tst/bbs/spcm-cntn/TEST_CNTN01
Content-Type: application/json
Accept: application/json
Cookie: accessToken={{accessToken}}; refreshToken={{refreshToken}}

###########################
# 검체 (Specimen)
###########################

### 검체 목록 조회 (전체)
GET {{api-service}}/api/tst/bbs/spcm
Content-Type: application/json
Accept: application/json
Cookie: accessToken={{accessToken}}; refreshToken={{refreshToken}}

### 검체 목록 조회 (검색: 이름 + 카테고리)
GET {{api-service}}/api/tst/bbs/spcm?spcmNm=test&spcmCateCd=01
Content-Type: application/json
Accept: application/json
Cookie: accessToken={{accessToken}}; refreshToken={{refreshToken}}

### 검체 단건 조회
GET {{api-service}}/api/tst/bbs/spcm/SPCM001
Content-Type: application/json
Accept: application/json
Cookie: accessToken={{accessToken}}; refreshToken={{refreshToken}}

### 검체 등록
POST {{api-service}}/api/tst/bbs/spcm
Content-Type: application/json
Accept: application/json
Cookie: accessToken={{accessToken}}; refreshToken={{refreshToken}}

{
  "spcmCd": "TEST_SPCM01",
  "spcmCateCd": "01",
  "spcmNm": "테스트 검체",
  "spcmAbbrNm": "테스트",
  "spcmEngNm": "Test Specimen",
  "spcmEngAbbrNm": "TestSpec",
  "useYn": true,
  "sortOrder": 1,
  "spcmCntnCd": "CNTN001",
  "saveTime": "24",
  "saveTimeUnit": "HOUR",
  "saveCond": "냉장",
  "engSaveCond": "Refrigerated",
  "caution": "주의사항",
  "engCaution": "Caution",
  "ref": "참고사항",
  "engRef": "Reference"
}

### 검체 수정
PUT {{api-service}}/api/tst/bbs/spcm/TEST_SPCM01
Content-Type: application/json
Accept: application/json
Cookie: accessToken={{accessToken}}; refreshToken={{refreshToken}}

{
  "spcmCateCd": "02",
  "spcmNm": "수정된 검체",
  "spcmAbbrNm": "수정",
  "spcmEngNm": "Updated Specimen",
  "spcmEngAbbrNm": "UpdSpec",
  "useYn": true,
  "sortOrder": 2,
  "spcmCntnCd": "CNTN002",
  "saveTime": "48",
  "saveTimeUnit": "HOUR",
  "saveCond": "냉동",
  "engSaveCond": "Frozen",
  "caution": "수정된 주의사항",
  "engCaution": "Updated Caution",
  "ref": "수정된 참고",
  "engRef": "Updated Reference"
}

### 검체 삭제
DELETE {{api-service}}/api/tst/bbs/spcm/TEST_SPCM01
Content-Type: application/json
Accept: application/json
Cookie: accessToken={{accessToken}}; refreshToken={{refreshToken}}
