package com.idrsys.ailis.sales.adapter.persistence.mapper

import com.idrsys.ailis.sales.application.dto.query.CustDetailInfo
import com.idrsys.ailis.sales.domain.model.Cust
import io.r2dbc.spi.Row
import java.time.LocalDate
import java.time.LocalDateTime

fun Row.toCustDetailInfo(): CustDetailInfo {
    return CustDetailInfo(
        custMstId = this.get("cust_mst_id", String::class.java),
        custCd = this.get("cust_cd", String::class.java)!!,
        custNm = this.get("cust_nm", String::class.java)!!,
        custDivCd = this.get("cust_div_cd", String::class.java)!!,
        directAcctCd = this.get("direct_acct_cd", String::class.java),
        directAcctNm = this.get("direct_acct_nm", String::class.java),
        directAcctAcctCd = this.get("direct_acct_acct_cd", String::class.java),
        rprsNm = this.get("rprs_nm", String::class.java),
        rstOutputCustNm = this.get("rst_output_cust_nm", String::class.java),
        careInstId = this.get("care_inst_id", String::class.java),
        custTypeCd = this.get("cust_type_cd", String::class.java)!!,
        bzoffiCd = this.get("bzoffi_cd", String::class.java),
        bzoffiPicId = this.get("bzoffi_pic_id", String::class.java),
        custStatCd = this.get("cust_stat_cd", String::class.java)!!,
        reqPossYn = this.get("req_poss_yn", Boolean::class.java)!!,
        rprsCustYn = this.get("rprs_cust_yn", Boolean::class.java)!!,
        rprsCustCd = this.get("rprs_cust_cd", String::class.java),
        rprsCustNm = this.get("rprs_cust_nm", String::class.java),
        studyProjCustYn = this.get("study_proj_cust_yn", Boolean::class.java)!!,
        studyProjNm = this.get("study_proj_nm", String::class.java),
        asrtCd = this.get("asrt_cd", String::class.java),
        careInstNo = this.get("care_inst_no", String::class.java),
        telNo = this.get("tel_no", String::class.java),
        faxNo = this.get("fax_no", String::class.java),
        zipcd = this.get("zipcd", String::class.java),
        addr1 = this.get("addr1", String::class.java),
        addr2 = this.get("addr2", String::class.java),
        reqDivCd = this.get("req_div_cd", String::class.java),
        atchFileGrupId = this.get("atch_file_grup_id", String::class.java),
        reqPossTstLimitYn = this.get("req_poss_tst_limit_yn", Boolean::class.javaObjectType),
        bizrno = this.get("bizrno", String::class.java),
        sapCustCd = this.get("sap_cust_cd", String::class.java),
        corpNo = this.get("corp_no", String::class.java),
        biznm = this.get("biznm", String::class.java),
        bztp = this.get("bztp", String::class.java),
        bzse = this.get("bzse", String::class.java),
        bizregRprsNm = this.get("bizreg_rprs_nm", String::class.java),
        openDt = this.get("open_dt", LocalDate::class.java),
        billPublYn = this.get("bill_publ_yn", Boolean::class.java)!!,
        addtaxInclYn = this.get("addtax_incl_yn", Boolean::class.java)!!,
        billPic = this.get("bill_pic", String::class.java),
        billPicEmaiAddr = this.get("bill_pic_emai_addr", String::class.java),
        billPicTelno = this.get("bill_pic_telno", String::class.java),
        billPublDt = this.get("bill_publ_dt", Integer::class.java)?.toInt(),
        payRtday = this.get("pay_rtday", Integer::class.java)?.toInt(),
        payPlanDt = this.get("pay_plan_dt", Integer::class.java)?.toInt(),
        payMethodCd = this.get("pay_method_cd", String::class.java),
        billAutoPublTargetYn = this.get("bill_auto_publ_target_yn", Boolean::class.java)!!,
        gccStmtMethodCd = this.get("gcc_stmt_method_cd", String::class.java)!!,
        spcmPickupMethodCd = this.get("spcm_pickup_method_cd", String::class.java),
        gcgPickupPicEmpNo = this.get("gcg_pickup_pic_emp_no", String::class.java),
        outamtWritingYn = this.get("outamt_writing_yn", Boolean::class.java)!!,
        frgnAcctYn = this.get("frgn_acct_yn", Boolean::class.java)!!,
        natnCd = this.get("natn_cd", String::class.java)!!,
        useLangCd = this.get("use_lang_cd", String::class.java)!!,
        crcyCd = this.get("crcy_cd", String::class.java)!!,
        custGradeCd = this.get("cust_grade_cd", String::class.java),
        branchCd = this.get("branch_cd", String::class.java),
        hpUrl = this.get("hp_url", String::class.java),
        taxDivCd = this.get("tax_div_cd", String::class.java)!!,
        rprsAcctBillCombPublYn = this.get("rprs_acct_bill_comb_publ_yn", Boolean::class.java)!!,
        truncUnitCd = this.get("trunc_unit_cd", String::class.java),
        invcEmailRecpYn = this.get("invc_email_recp_yn", Boolean::class.java)!!,
        invcRecpEmailAddr = this.get("invc_recp_email_addr", String::class.java),
        sotOutputYn = this.get("sot_output_yn", Boolean::class.java)!!,
        sotOutputQnty = this.get("sot_output_qnty", Integer::class.java)?.toInt()!!,
        rstNtcnRecpYn = this.get("rst_ntcn_recp_yn", Boolean::class.java)!!,
        rstNtcnRecpEmailAddr = this.get("rst_ntcn_recp_email_addr", String::class.java),
        reqMethodCd = this.get("req_method_cd", String::class.java),
        reqIfTypeCd = this.get("req_if_type_cd", String::class.java),
        creator = this.get("creator", String::class.java)!!,
        createDtime = this.get("create_dtime", LocalDateTime::class.java)!!,
        updater = this.get("updater", String::class.java)!!,
        updateDtime = this.get("update_dtime", LocalDateTime::class.java)!!
    )
}

internal fun Row.toCustMst(): Cust {
    return Cust(
        custMstId = this.get("cust_mst_id", String::class.java)!!,
        custCd = this.get("cust_cd", String::class.java)!!,
        custNm = this.get("cust_nm", String::class.java)!!,
        rstOutputCustNm = this.get("rst_output_cust_nm", String::class.java),
        rprsNm = this.get("rprs_nm", String::class.java),
        rprsCustYn = this.get("rprs_cust_yn", Boolean::class.java)!!,
        rprsCustCd = this.get("rprs_cust_cd", String::class.java),
        custDivCd = this.get("cust_div_cd", String::class.java)!!,
        directAcctCd = this.get("direct_acct_cd", String::class.java)!!,
        directAcctAcctCd = this.get("direct_acct_acct_cd", String::class.java),
        frgnAcctYn = this.get("frgn_acct_yn", Boolean::class.java)!!,
        studyProjCustYn = this.get("study_proj_cust_yn", Boolean::class.java)!!,
        studyProjNm = this.get("study_proj_nm", String::class.java),
        natnCd = this.get("natn_cd", String::class.java)!!,
        useLangCd = this.get("use_lang_cd", String::class.java)!!,
        crcyCd = this.get("crcy_cd", String::class.java)!!,
        custStatCd = this.get("cust_stat_cd", String::class.java)!!,
        reqPossYn = this.get("req_poss_yn", Boolean::class.java)!!,
        custTypeCd = this.get("cust_type_cd", String::class.java)!!,
        custGradeCd = this.get("cust_grade_cd", String::class.java),
        branchCd = this.get("branch_cd", String::class.java),
        bzoffiCd = this.get("bzoffi_cd", String::class.java),
        bzoffiPicId = this.get("bzoffi_pic_id", String::class.java),
        asrtCd = this.get("asrt_cd", String::class.java),
        zipcd = this.get("zipcd", String::class.java),
        addr1 = this.get("addr1", String::class.java),
        addr2 = this.get("addr2", String::class.java),
        hpUrl = this.get("hp_url", String::class.java),
        careInstNo = this.get("care_inst_no", String::class.java),
        careInstId = this.get("care_inst_id", String::class.java),
        bizrno = this.get("bizrno", String::class.java),
        corpNo = this.get("corp_no", String::class.java),
        bzse = this.get("bzse", String::class.java),
        bztp = this.get("bztp", String::class.java),
        biznm = this.get("biznm", String::class.java),
        bizregRprsNm = this.get("bizreg_rprs_nm", String::class.java),
        openDt = this.get("open_dt", LocalDate::class.java),
        billPublYn = this.get("bill_publ_yn", Boolean::class.java)!!,
        billAutoPublTargetYn = this.get("bill_auto_publ_target_yn", Boolean::class.java)!!,
        addtaxInclYn = this.get("addtax_incl_yn", Boolean::class.java)!!,
        taxDivCd = this.get("tax_div_cd", String::class.java)!!,
        billPic = this.get("bill_pic", String::class.java),
        billPicEmaiAddr = this.get("bill_pic_emai_addr", String::class.java),
        billPicTelno = this.get("bill_pic_telno", String::class.java),
        billPublDt = this.get("bill_publ_dt", Integer::class.java)?.toInt(),
        rprsAcctBillCombPublYn = this.get("rprs_acct_bill_comb_publ_yn", Boolean::class.java)!!,
        payRtday = this.get("pay_rtday", Integer::class.java)?.toInt(),
        payPlanDt = this.get("pay_plan_dt", Integer::class.java)?.toInt(),
        payMethodCd = this.get("pay_method_cd", String::class.java),
        gccStmtMethodCd = this.get("gcc_stmt_method_cd", String::class.java)!!,
        sapCustCd = this.get("sap_cust_cd", String::class.java),
        spcmPickupMethodCd = this.get("spcm_pickup_method_cd", String::class.java),
        gcgPickupPicEmpNo = this.get("gcg_pickup_pic_emp_no", String::class.java),
        truncUnitCd = this.get("trunc_unit_cd", String::class.java),
        invcEmailRecpYn = this.get("invc_email_recp_yn", Boolean::class.java)!!,
        invcRecpEmailAddr = this.get("invc_recp_email_addr", String::class.java),
        outamtWritingYn = this.get("outamt_writing_yn", Boolean::class.java)!!,
        sotOutputYn = this.get("sot_output_yn", Boolean::class.java)!!,
        sotOutputQnty = this.get("sot_output_qnty", Integer::class.java)?.toInt()!!,
        rstNtcnRecpYn = this.get("rst_ntcn_recp_yn", Boolean::class.java)!!,
        rstNtcnRecpEmailAddr = this.get("rst_ntcn_recp_email_addr", String::class.java),
        reqMethodCd = this.get("req_method_cd", String::class.java),
        reqIfTypeCd = this.get("req_if_type_cd", String::class.java),
        creator = this.get("creator", String::class.java)!!,
        createDtime = this.get("create_dtime", LocalDateTime::class.java)!!,
        updater = this.get("updater", String::class.java)!!,
        updateDtime = this.get("update_dtime", LocalDateTime::class.java)!!,
        reqDivCd = this.get("req_div_cd", String::class.java)!!,
        telNo = this.get("tel_no", String::class.java),
        faxNo = this.get("fax_no", String::class.java),
        atchFileGrupId = this.get("atch_file_grup_id", String::class.java),
        reqPossTstLimitYn = this.get("req_poss_tst_limit_yn", Boolean::class.java) ?: false,
        extnAuthKey = this.get("extn_auth_key", String::class.java)
    )
}
